[package]
name = "wallet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]

# internal
keypair.workspace = true
types.workspace = true

