[package]
name = "wallet-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
wallet.workspace = true
