[package]
name = "api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
solana-client.workspace = true
solana-sdk.workspace = true

# internal
model.workspace = true
