[package]
name = "keypair"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
bs58.workspace = true
ed25519-dalek.workspace = true

# internal
types.workspace = true
